# Use the official Nginx image as the base
FROM nginx:latest

# Copy custom configuration files if any (optional)
# COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Define the volume location for bind mount
VOLUME ["/var/opt/nginx"]

# Default command to run Nginx
CMD ["nginx", "-g", "daemon off;"]
